# Exceptions in C++
$NB$ **Любимая тема Вани**
Легко объяснимый механизм, который влияет на весь процесс написания кода.
Допустим мы пишем код: открываем файлик и что-то с ним делаем:
```c++
bool do_something() {
	FILE* file = fopen("1.txt");
	if (!file)
		return false;
	size_t bytes_read = fread(..., file);
	if (bytes_read < 0)
		return false;
	bytes_read = fread(..., file);
	if (bytes_read < 0)
		return false;
	bytes_read = fread(..., file);
	if (bytes_read < 0)
		return false;
	fclose(file);
	return true;
}
```
если в процессе возникает ошибка мы должны это отслеживать
Это неестественно, потому что засоряет код, требует дополнительных параметров(корректности операций). Вместо это мы могли бы читать и в случае ошибки "плеваться".
Для такой концепции был создан механизм исключений(_англ._ Exceptions)
## How does it works
```c++
void f() {
	if (...)
		throw runtime_error const& e("...");
}
```
`throw` работает как `return` - завершает выполнение ф-ии с каким-то кодом ошибки, а так же все наружные вызовы ее соответственно.
## Try - catch
```c++
try {
	...
	f();
	...
} catch (runtime_error const& e) {
	...
}
```
Выполняется сначала блок try если в нем ничего не произошло, код продолжает выполняться. Если ловится какой-то exception, то он переходит в соответствующий catch блок. Если такового нет, то исключение вылетает за пределы try-catch. 
Существует так же специальная форма catch, которая ловит все exception
```c++
catch (...) {
	...
	throw; //пробросить текущий(обрабатываемый) exception
}
```
**Примерчики**
```c++
struct base {
	virtual std::string msg() const {
		return "base";
	}
}
struct derived : base {
	std::string msg() const {
		return "derived";
	}
}
int main() {
	try {
		throw derived; //напечатает derived
		throw derived(); // без const в catch напечатает base
	} catch (base const& e) {
		std::cout << e.msg();
	}
}
```
Можно бросать `new` и ловить ссылку, но это идеоматически не верно. Нужен `delete` для `new` и все такое.
Другой код:
```c++
int main() {
	try {
		try {
			throw derived; //напечатает derived
		} catch (base & cinst & e1) {
			std::cout << e1.msg();
			throw; //а с этим выведет дважды derived
			throw e1; // интересный кейс, бросает статический тип,
			// а не динамический - скопируется. 
			//Следовательно она выведет derivedbase
		}
	} catch (base const& e) {
		std::cout << e.msg();
	}
}
```

Исключения часто используют для терминирования процессов(корректное преждевременное завершение).
Давайте перепишем старое:
```c++
void do_something() {
	FILE* file = fopen("1.txt");
	size_t bytes_read = fread(..., file);
	bytes_read = fread(..., file);
	bytes_read = fread(..., file);
	fcolse(file); 
}
void do_something2() {
	
}
```
Есть проблема, которая сохраняется с механизмом исключений: нам необходимо в любом случае закрыть файл, из которого мы что-то читаем.
В плюсах нет `finally`, вместо этого используется механизм деструкторов.
```c++
struct file_descriptor {
	file_descriptor(std::string const& filename) {
		file = fopen(filename.c_str());
		if (!file)
			throw ..;
	}
	size_t read();
	size_t write();
	file_descriptor(file_descriptor a) = delete;
	~file_descriptor() {
		fclose(file);
	}
};
```
`RAII - Resource Allocation Is Initialization`
Другой пример:
```c++
int main() {
	int* a = new int(5);
	int* b = new int(6);
	delete b;
	delete a;
}
```
Если `delete b` бросит исключение, то мы не удалим `a`
Фиксить это надо опять через структуры
```c++
struct unique_ptr() {
public:
	unique_ptr() : p(nullptr) {}
	explicit unique_ptr(int *p) : p(p) {}
	unique_ptr(unique_ptr const&) = delete;
	unique_ptr& operator=(unique_ptr const&) = delete;
	~unique_ptr() { delete p; }
	T& operator*() const { return *p; )
	T* operator ->() const { return p; }
private:
	T* p;
}
```
Такая штука есть в стандартной библиотеке. Там еще есть `get()` который достает указатель который внутри.
Конструктор не участвует в неявном копировании/приведении, если он `explicit`. Это создает хорошее правило:
> Надо думать должен ли какой-то тип иметь возможность быть неявно приведенным. Если не может - писать `explicit` у его конструктора.
## Гарантии исключений
От сильной к слабой:
* Не бросает никаких исключений (деструктор)
* Строгая - экземпляр не изменяется даже если бросится исключение
* ...

> Written with [StackEdit](https://stackedit.io/).
